# Default values for k8s-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# Individual component settings
web:
  replicaCount: 1
  image:
    repository: ghcr.io/ajh9789/web
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80

modelApi:
  replicaCount: 1
  image:
    repository: ghcr.io/ajh9789/model-api
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 8000
  env:
    TRANSFORMERS_CACHE: /models

modelWorker:
  replicaCount: 1
  image:
    repository: ghcr.io/ajh9789/model-worker
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: ClusterIP
    port: 80
  env:
    TRANSFORMERS_CACHE: /models
  resources:
    requests:
      memory: "4Gi"
      cpu: "1000m"
    limits:
      memory: "8Gi"
      cpu: "2000m"

redis:
  replicaCount: 1
  image:
    repository: redis
    pullPolicy: IfNotPresent
    tag: "7"
  service:
    type: ClusterIP
    port: 6379

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  #  kubernetes.io/ingress.class: nginx
  #  kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: model-api
            port: 8000
        - path: /
          pathType: Prefix
          service:
            name: web
            port: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Common settings for all pods
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
