apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    alertmanagerConfig: main
spec:
  route:
    receiver: slack-notifications
    groupBy: ['alertname', 'job'] # 2. 그룹핑 기준 추가
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    
  receivers:
  - name: "slack-notifications" # 1. 이름 단순화
    slackConfigs:
    - apiURL:
        key: slackUrl
        name: alertmanager-slack-secret
      channel: '#monitoring-alerts'
      sendResolved: true
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ else }}알림 발생{{ end }}'
      text: >-
        {{ range .Alerts -}}
        *요약 (Summary):* {{ .Annotations.summary }}
        *상세 (Description):* {{ .Annotations.description }}
        *발생 위치 (Instance):* `{{ .Labels.instance }}`
        *로그 확인:* <{{ .GeneratorURL }}|Prometheus Graph>
        ------------------------------------
        {{ end }}