apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
  labels:
    # 이 라벨이 있어야 Operator가 설정을 자동으로 불러옵니다.
    # ArgoCD의 릴리즈 이름과 일치해야 합니다.
    release: prometheus-stack
spec:
  route:
    # 모든 알림을 이 리시버로 보냅니다.
    receiver: 'slack-notifications'
    # 하위 규칙을 비워서 모든 알림이 위 리시버로 가도록 합니다.
    routes: []

  receivers:
  - name: 'slack-notifications'
    slackConfigs:
    - apiURL:
        # Slack Webhook URL이 저장된 Secret을 가리킵니다.
        key: slackUrl
        name: alertmanager-slack-secret
      channel: '#monitoring-alerts'
      sendResolved: true
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if .CommonLabels.alertname }}{{ .CommonLabels.alertname }}{{ else }}알림 발생{{ end }}'
      text: >-
        {{ range .Alerts -}}
        *요약 (Summary):* {{ .Annotations.summary }}
        *상세 (Description):* {{ .Annotations.description }}
        *발생 위치 (Instance):* `{{ .Labels.instance }}`
        *로그 확인:* <{{ .GeneratorURL }}|Prometheus Graph>
        ------------------------------------
        {{ end }}