apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-manager 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ajh9789/k8s-deploy'
    targetRevision: main
    path: k8s 
    directory:
      recurse: true
      
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true