apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alert
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: high-cpu-usage
    rules:
    - alert: HighCpuUsage
      #알림 조건 정의
      expr: cluster:node_cpu:ratio * 100 > 1 #쿼리문 수정
      for: 1m
      labels:
        severity: warning
      #알림 메시지 내용
      annotations:
        summary: "인스턴스 {{ $labels.instance }} CPU 사용량 높음"
        description: "인스턴스 {{ $labels.instance }}의 CPU 사용량이 임계치를 초과했습니다. 현재 사용량: {{ $value | printf `%.2f` }}%"