apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-alert
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: high-cpu-usage
    rules:
    - alert: HighCpuUsage
      #알림 조건 정의
      expr: vector(1)
        #100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 10 #쿼리문 수정
      for: 1m
      labels:
        severity: warning
      #알림 메시지 내용
      annotations:
        summary: "asd {{ $labels.instance }} asdads"
        description: "asad {{ $labels.instance }} Cdasdadasd: {{ $value | printf `%.2f` }}%."