apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.7.2
    helm:
      values: |
        loki:
          # 스토리지 설정을 azure로 변경
          storage:
            type: 'azure'
            azure:
              containerName: akslog # Blob 컨테이너 이름
              accountName:
                secretKeyRef:
                  name: loki-storage-secret
                  key: AZURE_STORAGE_ACCOUNT_NAME
              accountKey:
                secretKeyRef:
                  name: loki-storage-secret
                  key: AZURE_STORAGE_ACCOUNT_KEY
            bucketNames:
              chunks: akslog # 로그 데이터를 저장할 컨테이너
              ruler: akslog # 알림 규칙을 저장할 컨테이너
              admin: akslog # 관리자용 데이터를 저장할 컨테이너
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true