apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.0
    helm:
      values: |
        alertmanager:
          service:
            type: LoadBalancer
          # config 대신, 기존 Secret을 사용하라고 알려줍니다.
          config:
            existingSecret:
              name: alertmanager-config-secret
              key: alertmanager.yaml
        grafana:
          # 이 설정은 다른 부분에서 참조할 수 있으므로 유지합니다.
          existingSecret: "grafana-admin-credentials"
          # Grafana의 admin 계정 설정을 명확히 지정합니다.
          admin:
            existingSecret: "grafana-admin-credentials"
            userKey: adminUser
            passwordKey: adminPassword
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - grafana.prtest.shop
            tls:
              - secretName: grafana-prtest-shop-tls
                hosts:
                  - grafana.prtest.shop
        prometheus:
          service:
            type: LoadBalancer                 
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true #어노테이션 문제로 추가