apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT_NAME: your_storage_account
  AZURE_STORAGE_ACCOUNT_KEY: your_storage_key
  AZURE_CONTAINER_NAME: your_container