loki:
  read:
    extraVolumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
      
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"
    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key 
    extraArgs:
      - "-config.expand-env=true"

  write:
    extraVolumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true 
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"
    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key 
    extraArgs:
      - "-config.expand-env=true"

  backend:
    extraVolumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
      
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"
    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key 
    extraArgs:
      - "-config.expand-env=true"
      
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  test:
    enabled: false

  loki:
    config: |
      auth_enabled: false
      storage_config:
        azure:
          account_name: "stlokikanimator"
          container_name: "loki-logs"
          account_key: "$(AZURE_STORAGE_ACCOUNT_KEY)"

      schema_config:
        configs:
        - from: "2022-01-11"
          store: boltdb-shipper
          object_store: azure
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
    
  promtail:
    enabled: false