loki:
  deploymentMode: Distributed

  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0
  
  singleBinary:
    enabled: false

  distributor:
    replicas: 1    
    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
        
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"

    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key

    extraArgs:
      - "-config.expand-env=true"

    initContainers:
      - name: wait-for-csi-secret
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        command: ['sh','-c','echo "Waiting for secret file to be mounted..."; while [ ! -f /mnt/secrets-store/loki-storage-account-key ]; do ls -l /mnt/secrets-store; sleep 2; done; echo "Secret file found!"']      
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

  ingester:
    replicas: 1    
    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
        
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"

    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key

    extraArgs:
      - "-config.expand-env=true"

    initContainers:
      - name: wait-for-csi-secret
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        command: ['sh','-c','echo "Waiting for secret file to be mounted..."; while [ ! -f /mnt/secrets-store/loki-storage-account-key ]; do ls -l /mnt/secrets-store; sleep 2; done; echo "Secret file found!"']      
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

  querier:
    replicas: 1    
    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
        
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"

    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key

    extraArgs:
      - "-config.expand-env=true"

    initContainers:
      - name: wait-for-csi-secret
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        command: ['sh','-c','echo "Waiting for secret file to be mounted..."; while [ ! -f /mnt/secrets-store/loki-storage-account-key ]; do ls -l /mnt/secrets-store; sleep 2; done; echo "Secret file found!"']      
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true

  compactor:
    replicas: 1    
    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
        
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"

    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key

    extraArgs:
      - "-config.expand-env=true"

    initContainers:
      - name: wait-for-csi-secret
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        command: ['sh','-c','echo "Waiting for secret file to be mounted..."; while [ ! -f /mnt/secrets-store/loki-storage-account-key ]; do ls -l /mnt/secrets-store; sleep 2; done; echo "Secret file found!"']      
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true            

  queryFrontend:
    replicas: 1
    extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
        
    extraVolumes:
      - name: secrets-store-inline
        csi:
          driver: "secrets-store.csi.k8s.io"
          readOnly: true
          volumeAttributes:
            secretProviderClass: "loki-azure-provider"

    extraEnv:
      - name: AZURE_STORAGE_ACCOUNT_KEY
        valueFrom:
          secretKeyRef:
            name: loki-storage-secret 
            key: azure-storage-account-key

    extraArgs:
      - "-config.expand-env=true"

  loki:
    auth_enabled: false
    storage:
      type: azure
      azure:
        accountName: loki-storage-account
      bucketNames:
        chunks: loki-logs
        ruler:
          enabled: false

    schemaConfig:
      configs:
        - from: "2022-01-11"
          store: boltdb-shipper
          object_store: azure
          schema: v12
          index:
            prefix: loki_index_
            period: 24h


  monitoring:
    selfMonitoring:
      enabled: false
    grafanaAgent:
      installOperator: false

  test:
    enabled: false

  promtail:
    enabled: false