name: Build and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [web, model-api, model-worker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and Push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.CR_USERNAME }}/${{ matrix.service }}:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max