fluent-bit:
  image:
    tag: 4.0.7
  config:

    customParsers: |
      [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

      [PARSER]
        Name   app_log_parser
        Format regex
        Regex  ^\[(?<tag>[^\]]+)\]\s(?<message>.*)$
        
      [PARSER]
        Name   celery_log_parser
        Format regex
        Regex  ^\[(?<time>[^\]]+): (?<level>\w+)/(?<processName>[^\]]+)\] (?<message>.*)$

      [PARSER]
          Name   celery_extra_parser
          Format regex
          Regex  .*task_id:\s(?<task_id>[0-9a-f\-]+).*succeeded in (?<latency_s>[0-9\.]+)s.*
    service: |
      [SERVICE]
        Daemon      Off
        Log_Level   info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port   2020
        Parsers_File custom_parsers.conf

    inputs: |
      [INPUT]
          Name            systemd
          Tag             kube.*
          Path            /var/log/journal
          Read_From_Tail  On
          Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
          Systemd_Filter  _SYSTEMD_UNIT=containerd.service

    filters: |
      [FILTER]
        Name          kubernetes
        Match         kube.var.log.containers.*
        Merge_Log     On
        Keep_Log      Off

      [FILTER]
        Name                multiline
        Match               kube.*
        multiline.key_content    log
        multiline.parser        cri

      [FILTER]
        Name           rewrite_tag
        Match          kube.*
        Rule       $kubernetes['container_name'] ^model-worker$ kube.model-worker false
        Rule       $kubernetes['container_name'] ^model-api$ kube.model-api false
        Emitter_Name  re_emitted

      [FILTER]
        Name           parser
        Match          celery.logs
        Key_Name       log
        Parser         celery_log_parser
        Reserve_Data   On

      [FILTER]
        Name           parser
        Match          app.logs
        Key_Name       logs
        Parser         app_log_parser
        Reserve_Data   On

      [FILTER]
          Name         parser
          Match        celery.logs
          Key_Name     log
          Parser       celery_extra_parser
          Reserve_Data On

      [FILTER]
          Name      modify
          Match     *
          Condition Key_does_not_exist level
          Add       level unknown
    outputs: |
      [OUTPUT]
        Name        loki
        Match       *
        Host        loki-distributor.loki.svc.cluster.local
        Port        3100
        labels      job=fluent-bit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        line_format json