fluent-bit:
  image:
    tag: 4.0.7
  config:

    customParsers: |

    service: |
      [SERVICE]
        Daemon      Off
        Log_Level   info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port   2020
    #Parsers_File custom_parsers.conf

    inputs: |
      [INPUT]
          Name            systemd
          Tag             kube.*
          Path            /var/log/journal
          Read_From_Tail  On
          Systemd_Filter  _SYSTEMD_UNIT=kubelet.service
          Systemd_Filter  _SYSTEMD_UNIT=containerd.service

    filters: |

    outputs: |
      [OUTPUT]
        Name        loki
        Match       *
        Host        loki-distributor.loki.svc.cluster.local
        Port        3100
        line_format json

      [OUTPUT]
        Name   stdout
        Match  *
    #labels      job=fluent-bit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name'],level=$level
        