fluent-bit:
  config:
    customParsers: |
      [PARSER]
        Name   app_log_parser
        Format regex
        Regex  ^\[(?<tag>[^\]]+)\]\s(?<message>.*)$

      [PARSER]
        Name   celery_log_parser
        Format regex
        Regex  ^\[(?<time>[^\]]+): (?<level>\w+)/(?<processName>[^\]]+)\] (?<message>.*)$
    
    service: |
      [SERVICE]
        Daemon      Off
        Log_Level   info
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port   2020

    inputs: |
      [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        multiline.parser  cri
        Tag               kube.*
        Mem_Buf_Limit     5MB

    filters: |
      [FILTER]
        Name          kubernetes
        Match         kube.*
        Merge_Log     On
        Merge_Log_Key log_processed
        Keep_Log      Off

      [FILTER]
        Name           rewrite_tag
        Match          kube.*
        rule       $kubernetes['container_name'] ^model-worker$ kube.model-worker false
        rule       $kubernetes['container_name'] ^model-api$ kube.model-api false

      [FILTER]
        Name           parser
        Match          kube.*
        Key_Name       kubernetes.container_name
        Parser         app_log_parser
        Reserve_Data   Off

      [FILTER]
        Name           parser
        Match          kube.*
        Key_Name       kubernetes.container_name
        Parser         app_log_parser
        Reserve_Data   Off

      [FILTER]
        Name      modify
        Match     kube.*
        Condition message .*task_id:\s(?<task_id>[0-9a-f\-]+).*
        Add       task_id ${task_id}
        Condition message .*succeeded in (?<latency_s>[0-9\.]+)s.*
        Add       latency_s ${latency_s}

    outputs: |
      [OUTPUT]
        Name        loki
        Match       *
        Host        loki-distributor.loki.svc.cluster.local
        Port        3100
        Label_keys  $kubernetes['container_name'], $level
        Line_format json_nodate